### ISSUE TITLE
Had a crash while trying to start a server with Cursed

### ISSUE THREAD

**Issue by belathus** [Jusey1/Cursed#2]
Adding the mod to an existing server. I wouldn't be surprised if it saw the annihilation planes that I have placed in my base. Guessing the mod doesn't like the idea of a fake player breaking a block.

https://gist.github.com/belathus/9714bf989fe0ae98a2727e49400f468f

**Comment by Jusey1** [comment]
Nah, seems like I just need to add more != null checks. Update will be right out in a bit.
