### ISSUE TITLE
[Feature Request] Specify mobs immune to neutral aggro mechanic

### ISSUE THREAD

**Issue by OHKOBunny** [Jusey1/Cursed#3]
A blacklist would be very much appreciated since some mods add things that the curse renders aggro that shouldn't be. Not to mention even the mod this project derives from has an option to excuse bees specifically, but I would personally prefer tweaking the list to fit the needs of my pack

**Comment by Jusey1** [comment]
My mod doesn't work on Animals, so bees and wolves are excluded for example.

**Comment by Jusey1** [comment]
Also, there's already a blacklist. Been in the mod since the beginning, so am closing this.

**Comment by OHKOBunny** [comment]
Where? I'm not seeing it anywhere and this is all the config has
![where](https://github.com/Jusey1/Cursed/assets/52662321/595f0ecd-aca1-4938-be58-b68e19b6b9ae)

**Comment by Jusey1** [comment]
It's done via a datapack using the vanilla tag system: "curse/tags/entity_types/no_angry.json"

**Comment by OHKOBunny** [comment]
that's not quite the same, could you please add it to the main config file?

**Comment by Jusey1** [comment]
That's... Literally the exact same thing. I'm just using the vanilla system to give better control for modpack creators.
